### ISSUE TITLE
Tree warning?

### ISSUE THREAD

**Issue by nmshahir** [bryandmartin/corncob#27] opened 2018-11-26 22:54 UTC
Hello!

I'm currently trying corncob out on my data and noticed that if the physeq object contains a tree it has the following warning:
> In prune_taxa(taxa, phy_tree(x)) :
>   prune_taxa attempted to reduce tree to 1 or fewer tips.
>  tree replaced with NULL.

Is this intentional or?

**Comment by bryandmartin** [comment] 2019-01-12 22:55
Hi @nmshahir ,

Thanks for logging this issue! Could you provide more details here? I can't reproduce the issue. That is an error from a call to a phyloseq function. Does it occur when you call a corncob function?

Bryan

**Comment by gilsharon** [comment] 2019-02-13 01:29
Hi @bryandmartin, 

Sorry to jump in here, but I'm getting the same error - 
I'm new to corncob, so probably doing something wrong. I'm using a phyloseq object built from QIIME2 objects (and agglomerated by phyla):
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 8 taxa and 115 samples ]
sample_data() Sample Data:       [ 115 samples by 38 sample variables ]
tax_table()   Taxonomy Table:    [ 8 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 8 tips and 7 internal nodes ]

```
I tried running `differentialTest` and ran into a similar problem. it seems like the number of errors corresponds to the number of tips I have in my tree: 
```
> da_analysis <- differentialTest(formula = ~ cryopreservation,
+ phi.formula = ~ cryopreservation,
+ formula_null = ~ 1,
+ phi.formula_null = ~ cryopreservation,
+ test = "Wald", boot = FALSE,
+ data = cryo_male_fecal_phylum21to42,
+ fdr_cutoff = 0.05)
prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.prune_taxa attempted to reduce tree to 1 or fewer tips.
 tree replaced with NULL.Error in if (!all(mod$dat == mod_null$dat)) { : 
  missing value where TRUE/FALSE needed
```

I suppose the `if` statement there is the issue, because when I only pass an OTU table and the sample data I still get this error: 
```
> da_analysis <- differentialTest(formula = ~ cryopreservation,
+ phi.formula = ~ cryopreservation,
+ formula_null = ~ 1,
+ phi.formula_null = ~ cryopreservation,
+ test = "Wald", boot = FALSE,
+ data = otu_table(cryo_male_fecal_phylum21to42),
+ sample_data = sample_data(cryo_male_fecal_phylum21to42),
+ fdr_cutoff = 0.05)
Error in if (!all(mod$dat == mod_null$dat)) { : 
  missing value where TRUE/FALSE needed
```

any ideas ? 

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mctoolsr_0.1.1.2    vegan_2.5-4         lattice_0.20-35     permute_0.9-4       OMiAT_5.3          
 [6] forcats_0.3.0       stringr_1.4.0       dplyr_0.7.8         purrr_0.3.0         readr_1.3.1        
[11] tidyr_0.8.1         tibble_2.0.1        tidyverse_1.2.1     ggplot2_3.1.0       Biostrings_2.44.2  
[16] XVector_0.16.0      IRanges_2.10.5      S4Vectors_0.14.7    BiocGenerics_0.22.1 magrittr_1.5       
[21] phyloseq_1.25.2     breakaway_4.6.8     corncob_0.1.0      
```

**Comment by bryandmartin** [comment] 2019-02-13 09:15
Hi @gilsharon ,

This was an issue with checkNested, because `all()` cannot evaluate NAs in the data. I believe this was fixed in 3d24bac. Could you please try re-downloading corncob and trying again? Let me know if it fixes the issue or if you are still encountering problems!

Bryan

**Comment by bryandmartin** [comment] 2019-02-13 09:33
Thanks for the detailed write-up of the warning. I was now able to see that this warning comes from a warning in `phyloseq::prune_taxa()` (see line 500 of the [source code](https://github.com/joey711/phyloseq/blob/219c68164d34e48642d2a1e20ffa047906455233/R/transform_filter-methods.R)). This is just a warning that you are pruning to a single OTU, which is of course exactly the goal of the `corncob::convert_phylo()`. 

The warning didn't affect any analysis, but it is now suppressed as of 97ccb1e.

**Comment by gilsharon** [comment] 2019-02-13 16:07
Hi @bryandmartin, thanks for the quick response! 
removed and installed corncob, but no luck - I'm getting the same warning, as well as an error right after (maybe a separate issue?). 

Any idea what's the cause for this error? I'm not too troubled by the warning at this point. 

thanks! 
Gil

`Error in if (!all(mod$dat == mod_null$dat)) { : 
  missing value where TRUE/FALSE needed`

**Comment by gilsharon** [comment] 2019-02-13 18:32
@bryandmartin, Just realized I didn't restart my R session before trying again. 
Your fix solved the issue, Thanks!

**Comment by bryandmartin** [comment] 2019-02-13 18:41
@gilsharon 

Great, thank you, and thanks for helping me solve this old issue!

**Closed by bryandmartin** 2019-02-13 18:41 UTC
