### ISSUE TITLE
Error in trust::trust -- parinit not feasible

### ISSUE THREAD

**Issue by adw96** [bryandmartin/corncob#59] opened 2019-08-15 20:31 UTC
Hi @bryandmartin! I've got a dataset that is breaking `trust::trust`:

> Error in trust::trust(objfun, parinit = theta.init, W = W, M = M, X = X.b,  : 
  parinit not feasible

```
library(tidyverse)
breaks_corn <- structure(list(W = c(22012, 59233, 223268, 122825, 53763, 29208, 
                     20568, 175146, 242484, 3069, 29495, 461774, 277620, 425460, 47622, 
                     268909, 133373, 232651, 201, 81882, 81301, 6125, 132758, 143665, 
                     74543, 34721, 10149, 4575, 2217, 85642, 289783, 35408, 10529, 
                     36338, 83723, 75024, 18172, 12845, 118999, 17063, 170357, 45213, 
                     6455, 72889, 114416, 338174, 18268, 99339, 134994, 74336, 4335, 
                     6503, 34263, 146457, 30725, 54379, 62320, 5825, 573, 418272, 
                     22355, 450960, 266391, 239118, 95671, 17589, 109710, 151699, 
                     1076, 2278, 202113, 157465, 94524, 308358, 60273, 70820, 97379, 
                     235883, 150704, 466330, 660503, 75217, 1873, 558812, 113987, 
                     68933, 205555, 280552, 19630, 1847, 13782, 79365, 20071, 350286, 
                     91333, 515, 801971, 346819, 16109, 40779, 92535, 78280, 113517, 
                     32868, 138647, 14270, 117617, 47739, 107495, 12350, 77869, 37222, 
                     248932, 68421, 49951, 2481, 132092, 38095, 58736, 252037, 169843, 
                     39361, 39701, 33712, 332291, 205788, 84891, 36467, 52626, 22417, 
                     10488, 54524, 89814, 129946, 157795, 41366, 151332, 253242, 46999, 
                     216132, 73530, 40310, 2421), M = c(6188331, 11432135, 9071216, 
                                                        8856043, 7600919, 7310208, 1793383, 7276145, 9605078, 13603589, 
                                                        7893161, 14845141, 13972354, 16163738, 11098252, 15797133, 16727169, 
                                                        14325755, 14169519, 14849646, 12321433, 11356091, 6141549, 7367357, 
                                                        5546644, 7184518, 6675717, 5388676, 5559357, 9755207, 9321726, 
                                                        9023634, 2803159, 9562367, 6882326, 5514297, 8460187, 6701281, 
                                                        8116523, 2877017, 8124274, 8091025, 1995441, 7200738, 9781964, 
                                                        9913532, 6988329, 8092894, 9142106, 4765359, 11357280, 6690537, 
                                                        2293559, 7354137, 7336240, 8521415, 8509766, 8027941, 10796926, 
                                                        10565994, 7530208, 8511576, 11255767, 11206524, 7456083, 5966828, 
                                                        9071099, 8483974, 8161814, 5576187, 8496265, 6056579, 7885259, 
                                                        8506625, 16497934, 9169591, 10478059, 13309231, 17638017, 13806592, 
                                                        16827390, 18019971, 6622133, 11867686, 8551369, 5839951, 21206918, 
                                                        15032242, 10882909, 11157812, 2291965, 16656335, 3348443, 17769050, 
                                                        15360414, 10409531, 18071928, 17095556, 2950090, 13968352, 13400391, 
                                                        14778644, 13675474, 7875209, 14793548, 12932461, 13340486, 18289402, 
                                                        9782114, 12962250, 15451028, 8229705, 14663503, 14253617, 3289372, 
                                                        16912942, 8727386, 12024105, 16372540, 12686343, 8195228, 9090207, 
                                                        11006956, 8046474, 13301476, 11472474, 20224012, 10786250, 12684928, 
                                                        12972200, 5471791, 3037373, 6146142, 4207054, 3678159, 7310788, 
                                                        4678621, 4992290, 4573959, 8524345, 6191269, 7374788, 7583572
                     ), X = c(95.70894677, 47.85447339, 43.147476, 77.66545681, 90.21744983, 
                              148.2704175, 72.17395986, 52.56147077, 106.6919407, 79.23445594, 
                              91.78644896, 32.94898168, 65.11346379, 117.674934599999, 47.06997382, 
                              92.57094852, 131.7959267, 70.60496073, 103.5539424, 80.0189555, 
                              163.1759093, 117.674934599999, 75.31195812, 54.1304699, 65.89796335, 
                              111.398937999999, 94.13994765, 313.7998255, 152.977414899999, 
                              90.21744983, 285.5578412, 98.84694503, 54.1304699, 157.6844123, 
                              76.88095724, 65.11346379, 72.95845943, 72.95845943, 55.69946902, 
                              73.74295899, 89.43295026, 183.5728979, 66.68246292, 135.7184245, 
                              70.60496073, 106.6919407, 72.95845943, 42.36297644, 80.80345506, 
                              85.51045245, 74.52745855, 105.907441099999, 61.19096597, 120.8129328, 
                              74.52745855, 53.34597033, 80.0189555, 80.0189555, 127.8734289, 
                              131.0114271, 71.3894603, 498.157223, 97.2779459, 121.5974324, 
                              79.23445594, 185.141897, 98.06244547, 168.6674062, 69.03596161, 
                              271.436849, 97.2779459, 78.44995637, 77.66545681, 79.23445594, 
                              73.74295899, 83.15695375, 128.6579285, 203.185387, 123.9509311, 
                              67.46696248, 50.99247164, 99.63144459, 112.183437599999, 38.44047862, 
                              49.42347251, 98.84694503, 225.9358744, 89.43295026, 123.166431499999, 
                              38.44047862, 43.147476, 122.3819319, 61.97546553, 81.58795463, 
                              59.62196684, 279.281844699999, 92.57094852, 138.0719232, 87.07945157, 
                              57.26846815, 58.83746728, 164.7449084, 34.5179808, 174.1589031, 
                              107.4764402, 88.6484507, 62.7599651, 127.0889293, 80.80345506, 
                              55.69946902, 240.8413661, 45.5009747, 80.80345506, 94.13994765, 
                              261.2383547, 76.09645768, 54.91496946, 61.97546553, 136.5029241, 
                              180.4348997, 135.7184245, 96.49344634, 157.6844123, 61.19096597, 
                              85.51045245, 75.31195812, 57.26846815, 94.13994765, 102.7694428, 
                              257.3158569, 71.3894603, 72.17395986, 90.21744983, 53.34597033, 
                              49.42347251, 65.89796335, 55.69946902, 160.037911, 69.03596161, 
                              43.147476, 112.9679372, 61.19096597, 80.80345506)), row.names = c(NA, 
                                                                                                -143L), class = c("tbl_df", "tbl", "data.frame"))
breaks_corn %>%
  bbdml(formula = cbind(W, M - W) ~ X,
        phi.formula = ~ X,
        data = .)
```

Help appreciated!

**Comment by bryandmartin** [comment] 2019-08-20 20:24
Hi Amy, I am unable to reproduce this issue. Could you please try installing the newest version of corncob and letting me know if this still occurs for you?

**Comment by bryandmartin** [comment] 2019-10-24 20:21
Hi @adw96 ,

Strangely, I was never able to reproduce this error from this data, but as of abba876, I believe it should be fixed. Could you let me know?

**Closed** 2019-11-03 20:31 UTC
